---
driver:
  name: docker
  require_chef_omnibus: false
  require_ruby_for_busser: false
  use_sudo: false

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu

provisioner:
  ansible_connection: ssh
  ansible_host_key_checking: false
  ansible_version: latest
  custom_pre_play_command: sudo chown -R kitchen:kitchen /home/kitchen/.ansible
  name: ansible_playbook
  hosts: test-kitchen
  idempotency_test: true
  require_ansible_repo: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  requirements_path: ./test/integration/requirements.yml
  role_name: ansible-sngrep-mw
  roles_path: .

suites:
  - name: default

transport:
  max_ssh_sessions: 6

verifier:
  name: inspec
