---
# Uncommend the following section to enable parallel builds
# using the Travis-CI build matrix feature
# FOR DETAILS SEE README!
# env:
#   - kitchen_instance=default-ubuntu-1404
#   - kitchen_instance=default-ubuntu-1604
language: ruby
rvm:
  - 2.3
sudo: required

services:
  - docker

before_install: "./test/scripts/before-install.sh"
install: "./test/scripts/install.sh"
script: "./test/scripts/test-role.sh"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
