---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Sngrep.
  package:
    name: "{{ sngrep_package }}"
    state: "{{ sngrep_package_state }}"
