---
- name: Add Irontec key.
  rpm_key:
    key: "{{ irontec_key_url_repository }}"
    state: present

- name: Add Irontec repository.
  yum_repository:
    name: irontec
    description: Irontec repository
    baseurl: "{{ sngrep_yum_repo_url }}"
