---
- name: Add Irontec key.
  rpm_key:
    key: {{ irontec_key_url_repository }}
    state: present

- name: Add Irontec repository.
  get_url:
    url: "{{ irontec_yum_repo_url }}"
    dest: '/etc/yum.repos.d/irontec.repo'
    owner: root
    group: root
    mode: 0644
