---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
  - name: instance
    image: debian:8
  - name: instance
    image: debian:9
  - name: instance
    image: ubuntu:16.04
  - name: instance
    image: ubuntu:18.04
rovisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
